name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      !startsWith(github.event.pull_request.head.label, 'heineiuo:')

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
   
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm install
        env:
          CI: true

      - name: Build
        run: |
          npm run build
          npm run dts
        env:
          CI: true


      - name: Create Changelogs
        if: |
          github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        id: changelog
        uses: heineiuo/create-changelogs@master

      - name: NPM Publish
        if: |
          github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          echo '//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}' > ~/.npmrc
          npm publish

      - name: Github Release
        if: |
          github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # name: ${{ github.ref }}
          draft: false
          # artifacts: "website_id.txt"
          body: ${{ steps.changelog.outputs.changelogs }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease:
            ${{ steps.changelog.outputs.release_type == 'prerelease' }}